package com.ebabu.event365live.host.DI;


import com.ebabu.event365live.host.AddNewAccountFragment;
import com.ebabu.event365live.host.ChooseBankAccountFragment;
import com.ebabu.event365live.host.ConfirmWithdrawFragment;
import com.ebabu.event365live.host.WithdrawFragment;
import com.ebabu.event365live.host.activity.CheckedInRSVP;
import com.ebabu.event365live.host.activity.EditEventDetails;
import com.ebabu.event365live.host.activity.EventDetails;
import com.ebabu.event365live.host.activity.ForgotPassword;
import com.ebabu.event365live.host.activity.Home;
import com.ebabu.event365live.host.activity.InviteRSVPActivity;
import com.ebabu.event365live.host.activity.Login;
import com.ebabu.event365live.host.activity.NotificationActivity;
import com.ebabu.event365live.host.activity.ProfileActivity;
import com.ebabu.event365live.host.activity.Register;
import com.ebabu.event365live.host.activity.RegisterVanue;
import com.ebabu.event365live.host.activity.ResetPassword;
import com.ebabu.event365live.host.activity.SMSVerification;
import com.ebabu.event365live.host.activity.SearchVenueActivity;
import com.ebabu.event365live.host.activity.UpdateTicketActivity;
import com.ebabu.event365live.host.activity.VenueDetail;
import com.ebabu.event365live.host.activity.VerifiyCode;
import com.ebabu.event365live.host.activity.ui.ImageCropperActivity;
import com.ebabu.event365live.host.activity.ui.home.HomeFragment;
import com.ebabu.event365live.host.activity.ui.home.HomeViewModel;
import com.ebabu.event365live.host.adapter.AllRSVPAdapter;
import com.ebabu.event365live.host.adapter.CheckedInRSVPAdapter;
import com.ebabu.event365live.host.adapter.DaysAdapter;
import com.ebabu.event365live.host.adapter.EventAdapter;
import com.ebabu.event365live.host.adapter.GalleryAdapter;
import com.ebabu.event365live.host.adapter.GalleryPicAdapter;
import com.ebabu.event365live.host.adapter.InviteRsvpAdapter;
import com.ebabu.event365live.host.adapter.PaymentAdapter;
import com.ebabu.event365live.host.adapter.PreviousVenueAdapter;
import com.ebabu.event365live.host.adapter.ReviewAdapter;
import com.ebabu.event365live.host.adapter.SearchVenueAdapter;
import com.ebabu.event365live.host.adapter.SelectSubVenueAdapter;
import com.ebabu.event365live.host.adapter.SubVenueAdapter;
import com.ebabu.event365live.host.adapter.VenueAdapter;
import com.ebabu.event365live.host.adapter.VenuePicInEventAdapter;
import com.ebabu.event365live.host.bankdetails.fragment.CompletedPaymentFrag;
import com.ebabu.event365live.host.bankdetails.fragment.PendingHistoryFrag;
import com.ebabu.event365live.host.fragments.AllRSVPFragment;
import com.ebabu.event365live.host.fragments.CheckedInRSVPFragment;
import com.ebabu.event365live.host.fragments.CreateEventFragment;
import com.ebabu.event365live.host.fragments.CreateEventFullEvent;
import com.ebabu.event365live.host.fragments.EventNotificationFragment;
import com.ebabu.event365live.host.fragments.MinPaymentFragment;
import com.ebabu.event365live.host.fragments.MyProfile;
import com.ebabu.event365live.host.fragments.NoCheckedInRSVPFragment;
import com.ebabu.event365live.host.fragments.PaymentFragment;
import com.ebabu.event365live.host.fragments.PaymentMethodFragment;
import com.ebabu.event365live.host.fragments.ProfileNotificationFragment;
import com.ebabu.event365live.host.fragments.RSVPNotificationFragment;
import com.ebabu.event365live.host.fragments.SettingFragment;
import com.ebabu.event365live.host.fragments.TransactionNotificationFragment;
import com.ebabu.event365live.host.fragments.edit_ticket.EditTicktActivity;
import com.ebabu.event365live.host.fragments.rsvp_invites.AllContactSFragment;
import com.ebabu.event365live.host.fragments.rsvp_invites.MyContactsFragment;
import com.ebabu.event365live.host.fragments.rsvp_invites.PastAttendeesFragment;
import com.ebabu.event365live.host.fragments.rsvp_invites.adapter.MyContactAdapter;
import com.ebabu.event365live.host.fragments.rsvp_invites.adapter.PastAttendeesAdapter;
import com.ebabu.event365live.host.fragments.ticket.FullEventDetailFragment;
import com.ebabu.event365live.host.repositories.ProfileRepository;
import com.ebabu.event365live.host.viewmodels.AddUserViewModel;
import com.ebabu.event365live.host.viewmodels.CreateEventViewModel;
import com.ebabu.event365live.host.viewmodels.EventDetailsViewModel;
import com.ebabu.event365live.host.viewmodels.ManageUserViewModel;
import com.ebabu.event365live.host.viewmodels.PastEventViewModel;
import com.ebabu.event365live.host.viewmodels.ProfileViewModel;
import com.ebabu.event365live.host.viewmodels.SearchVenueViewModel;
import com.ebabu.event365live.host.viewmodels.SignUpViewModel;
import com.ebabu.event365live.host.viewmodels.UpcomingEventsViewModel;
import com.ebabu.event365live.host.viewmodels.VenueViewModel;

import javax.inject.Singleton;


import dagger.Component;

@Singleton
@Component(modules = {RetrofitModule.class,ContextModule.class})
public interface AppComponent {
    void inject(SignUpViewModel clazz);
    void inject(VerifiyCode clazz);
    void inject(Login clazz);
    void inject(SMSVerification clazz);
    void inject(HomeViewModel clazz);
    void inject(VenueAdapter clazz);
    void inject(RegisterVanue clazz);
    void inject(VenueViewModel clazz);
    void inject(UpcomingEventsViewModel clazz);
    void inject(PastEventViewModel clazz);
    void inject(ManageUserViewModel clazz);
    void inject(AddUserViewModel clazz);
    void inject(CreateEventViewModel clazz);
    void inject(EventDetailsViewModel clazz);
    void inject(VenueDetail clazz);
    void inject(ForgotPassword clazz);
    void inject(ResetPassword clazz);
    void inject(EventAdapter clazz);
    void inject(ProfileViewModel clazz);
    void inject(ProfileActivity clazz);
    void inject(MyProfile clazz);
    void inject(ReviewAdapter clazz);
    void inject(GalleryAdapter clazz);
    void inject(VenuePicInEventAdapter clazz);
    void inject(CreateEventFragment clazz);
    void inject(CreateEventFullEvent clazz);
    void inject(MinPaymentFragment clazz);
    void inject(PaymentMethodFragment clazz);
    void inject(EditEventDetails clazz);
    void inject(EventDetails clazz);
    void inject(NotificationActivity clazz);
    void inject(HomeFragment clazz);
    void inject(CheckedInRSVPFragment clazz);
    void inject(CheckedInRSVPAdapter clazz);
    void inject(NoCheckedInRSVPFragment clazz);
    void inject(AllRSVPFragment clazz);
    void inject(AllRSVPAdapter clazz);
    void inject(InviteRSVPActivity clazz);
    void inject(InviteRsvpAdapter clazz);
    void inject(PaymentFragment clazz);
    void inject(PaymentAdapter clazz);
    void inject(ProfileRepository clazz);
    void inject(CheckedInRSVP clazz);
    void inject(UpdateTicketActivity clazz);
    void inject(WithdrawFragment clazz);
    void inject(AddNewAccountFragment clazz);
    void inject(ChooseBankAccountFragment clazz);
    void inject(ConfirmWithdrawFragment clazz);
    void inject(PendingHistoryFrag clazz);
    void inject(CompletedPaymentFrag clazz);
    void inject(SettingFragment clazz);
    void inject(Home clazz);
    void inject(EventNotificationFragment clazz);
    void inject(RSVPNotificationFragment clazz);
    void inject(TransactionNotificationFragment clazz);
    void inject(ProfileNotificationFragment clazz);
    void inject(GalleryPicAdapter clazz);
    void inject(ImageCropperActivity clazz);
    void inject(FullEventDetailFragment clazz);
    void inject(Register clazz);
    void inject(EditTicktActivity clazz);
    void inject(SearchVenueActivity clazz);
    void inject(SearchVenueAdapter clazz);
    void inject(SubVenueAdapter clazz);
    void inject(DaysAdapter clazz);
    void inject(PreviousVenueAdapter clazz);
    void inject(SelectSubVenueAdapter clazz);
    void inject(AllContactSFragment clazz);
    void inject(MyContactsFragment clazz);
    void inject(MyContactAdapter clazz);
    void inject(PastAttendeesFragment clazz);
    void inject(PastAttendeesAdapter clazz);
    void inject(SearchVenueViewModel clazz);
}
